/**
 * Turns the fetched photographs into something the app can import.
 *
 * Two jobs. First, the credit: a CC BY-SA image may not be shipped without
 * naming the photographer and the licence, so the manifest is generated rather
 * than hand-written and the app reads the credit from the same record that
 * produced the file. There is no way to add a photograph here and forget to
 * credit it.
 *
 * Second, the placeholder. A 24px copy of each photograph, inlined as a data
 * URI and scaled up under a blur, gives the tile its final colour immediately
 * and lets the full image cross-fade in over it. The alternative -- an empty
 * grey rectangle that snaps to a photograph -- is the single most obvious tell
 * of an unfinished page.
 */

import { execFileSync } from "node:child_process"
import fs from "node:fs/promises"
import os from "node:os"
import path from "node:path"

const MANIFEST = path.join(process.cwd(), "data", "raw", "photos.json")
const OUT = path.join(process.cwd(), "src", "data", "photos.ts")
const PHOTOS = path.join(process.cwd(), "public", "photos")

/** A 24px-wide JPEG of the file, base64'd. `sips` ships with macOS. */
async function placeholder(file, tmp) {
    const dest = path.join(tmp, path.basename(file))
    execFileSync("sips", ["-Z", "24", "-s", "format", "jpeg", "-s", "formatOptions", "35", file, "--out", dest], {
        stdio: "ignore",
    })
    const buf = await fs.readFile(dest)
    return `data:image/jpeg;base64,${buf.toString("base64")}`
}

/** Dimensions of the file as it actually shipped, post-resize. */
function dimensions(file) {
    const out = execFileSync("sips", ["-g", "pixelWidth", "-g", "pixelHeight", file], { encoding: "utf8" })
    return {
        width: Number(out.match(/pixelWidth:\s*(\d+)/)?.[1] ?? 0),
        height: Number(out.match(/pixelHeight:\s*(\d+)/)?.[1] ?? 0),
    }
}

const raw = JSON.parse(await fs.readFile(MANIFEST, "utf8"))
const tmp = await fs.mkdtemp(path.join(os.tmpdir(), "civicflow-lqip-"))

const photos = []
for (const p of raw.photos) {
    const file = path.join(PHOTOS, path.basename(p.src))
    try {
        await fs.access(file)
    } catch {
        console.warn(`  ✗ ${p.slug}: file missing, dropped from manifest`)
        continue
    }
    photos.push({ ...p, ...dimensions(file), blur: await placeholder(file, tmp) })
    console.log(`  ✓ ${p.slug}`)
}
await fs.rm(tmp, { recursive: true, force: true })

const body = `/**
 * GENERATED by scripts/build-photos.mjs. Do not edit.
 *
 * Photographs of the places the model runs on, from Wikimedia Commons, each
 * under a licence that permits reuse. \`credit\` and \`licence\` are not optional
 * metadata: CC BY and CC BY-SA require attribution, so the component that
 * renders a photograph renders its credit.
 *
 * \`blur\` is a 24px copy of the same image, inlined so a tile has its colour
 * before any network request completes.
 */

export interface Photo {
    /** Key the app refers to, e.g. "bentonville". */
    slug: string
    /** The place shown, as it should be captioned. */
    place: string
    /** County it sits in, which is how a photograph joins to modelled figures. */
    county: string
    /** Original file name on Commons. */
    file: string
    credit: string
    licence: string
    licenceUrl: string | null
    /** Commons file page, for the credit link. */
    source: string
    src: string
    width: number
    height: number
    /** Inlined 24px placeholder, blurred up while the photograph loads. */
    blur: string
}

export const PHOTOS: Photo[] = ${JSON.stringify(photos, null, 4)}

const BY_SLUG = new Map(PHOTOS.map((p) => [p.slug, p]))

export function photo(slug: string): Photo | undefined {
    return BY_SLUG.get(slug)
}

/** Every photograph taken in a given county, for joining to zone figures. */
export function photosInCounty(county: string): Photo[] {
    return PHOTOS.filter((p) => p.county === county)
}

export const PHOTO_SOURCE = "Wikimedia Commons"
export const PHOTO_FETCHED_AT = ${JSON.stringify(raw.fetchedAt)}
`

await fs.mkdir(path.dirname(OUT), { recursive: true })
await fs.writeFile(OUT, body)
console.log(`\n${photos.length} photographs → src/data/photos.ts`)
